name: Build and Push Docker image

on:
  push:
    branches: [ "principal" ]  # Asegúrate que sea 'principal' si ese es el nombre de tu rama

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: lucia1982/vzeta-nginx:latest
